### ISSUE TITLE
Keyboard doesn't seen for Sample.qml's example

### ISSUE THREAD

**Issue by edips** [MidoriYakumo/qml-virtualkey#2]
Hello.Keyboard doesn't seen for "simple" example. Thanks for the project. 
OS is Manjaro

**Comment by MidoriYakumo** [comment]
Do you mean some error like 'module "VirtualKey" is not installed'?
use qmlscene -I path_to_qml-virtualkey to add import search path

**Comment by edips** [comment]
I added Virtualkeyboard folder to 5.11/gcc/qml/ path. Other examples works great. Only I was unable to run simple example properly like this picture:
![virtualkeyboard](https://user-images.githubusercontent.com/3856713/50314022-62d60000-04be-11e9-80d0-66fc8f070a6f.png)

**Comment by MidoriYakumo** [comment]
The underlying QtQuickControls2 Button type has changed, VirtualKey/VirtualKey.qml:175 should be paintedWidth -> implicitWidth

**Comment by edips** [comment]
Thank you, it works great now :)
